### ISSUE TITLE
set org in foia creation

### ISSUE THREAD

**Issue by fgregg** [datadesk/python-muckrock#14]
is it possible to set the organization that a FOIA request is associated with? it looks like that might not be supported by the muckrock API, but thought i'd double check with you.

**Comment by palewire** [comment]
I haven't tried to figure this one out before. Looking quickly at the MuckRock source code here on GitHub, I wonder if the key bit might be here: https://github.com/MuckRock/muckrock/blob/master/muckrock/foia/viewsets.py#L251

It's not clear to me what the implications of that would be. You got a read?

**Comment by fgregg** [comment]
it doesn't really look like that's something that can be changed in the API.

**Comment by palewire** [comment]
It might be worth asking the MuckRock core team. It wouldn't surprise me if they would make this change for you.

**Comment by fgregg** [comment]
word! i did send them a note.
